targets:
  $default:
    builders:
      repo_case_generator|repo_case:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*

builders:
  repo_case:
    import: "package:repo_case_generator/builder.dart"
    builder_factories: ["repoCaseGenerator"]
    build_extensions: { ".dart": [".rc.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["injectable_generator|injectable_builder"]
