name: repo_case_generator
description: Generator package for repo_case to auto-generate use cases classes from your repository signature class
author: Sandro Maglione <lass.maglio@gmail.com>
homepage: https://github.com/SandroMaglione/repo_case.dart 

version: 0.2.0-nullsafety.0

environment:  
  sdk: ">=2.12.0-0 <3.0.0" 
  
dependencies:  
  build: ">=0.12.6 <2.0.0"  
  source_gen: ^0.9.6
  path: ^1.8.0-nullsafety.3
  # code_builder: ^3.4.0
  analyzer: ^0.40.6
  
  # repo_case: 
    # path: ../repo_case/ 
  repo_case: ^0.1.2

dev_dependencies:  
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.16.0-nullsafety.13
  source_gen_test: ^0.1.1+1
  # mockito: ^4.1.3