name: repo_case_generator
description: Generator package for repo_case.
version: 0.1.0
author: Sandro Maglione <lass.maglio@gmail.com>
homepage: https://github.com/SandroMaglione/repo_case.dart 

environment:  
  sdk: ">=2.6.0 <3.0.0" 
  
dependencies:  
  build: ">=0.12.6 <2.0.0"  
  source_gen: ^0.9.6
  code_builder: ^3.4.0
  repo_case:    
    path: ../repo_case/  

dev_dependencies:  
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.6.0

dependency_overrides:
  analyzer: '0.39.14'