name: repo_case_generator
description: Generator package for repo_case to auto-generate use cases classes from your repository signature class
author: Sandro Maglione <lass.maglio@gmail.com>
homepage: https://github.com/SandroMaglione/repo_case.dart 

version: 0.2.0-nullsafety.2

environment:  
  sdk: ">=2.12.0 <3.0.0" 
  
dependencies:  
  build: ^2.0.0 
  source_gen: ^1.0.0
  path: ^1.8.0-nullsafety.3
  # code_builder: ^3.4.0
  analyzer: ^1.1.0
  
  # repo_case: 
    # path: ../repo_case/ 
  repo_case: ^0.2.0-nullsafety.0

dev_dependencies:  
  build_test: ^2.0.0
  build_runner: ^1.11.1
  test: ^1.16.5
  source_gen_test: ^1.0.0
  # mockito: ^4.1.3